### ISSUE TITLE
Opening an issue

### ISSUE THREAD

**Issue by cmaddux** [MichaelIrvine/mfi-portfolio-photo#1]
Hey @MichaelIrvine just opening an issue to chat!

If this isn't the repository you were thinking about opening an issue in, just @mention me in another repo.

**Comment by MichaelIrvine** [comment]
That works! ha

**Comment by MichaelIrvine** [comment]
Sorry. still new to all this

**Comment by MichaelIrvine** [comment]
I was wondering if you wouldn't mind checking out some js for me...

First thing: Any suggestions on how to slim down some of this code?

Second: Is it possible to make items clickable only if they meet certain requirements? Such as...
if "items" are **not** past a scroll position then they cannot be clicked.

This is what I've been trying.

`jQuery(document).ready(function($) {
  // Desktop menu hide on scroll
  $(window).scroll(function() {
    var y_scroll_pos = window.pageYOffset;
    var scrollPosition = 250;
    var $menuList = $(".menu-item-23, .menu-item-24, .menu-item-25");

    // Hides menu when viewer scrolls down
    if (y_scroll_pos > scrollPosition) {
      $menuList.addClass("hide-menu");
    } else {
      $menuList.removeClass("hide-menu");
    }

    // Makes the Menu lines move 

    // ----------- Top line ----------------------------
    if (y_scroll_pos > scrollPosition) {
      $(".line-one").addClass("line-one-animate");
    } else {
      $(".line-one").removeClass("line-one-animate");
    }

    // ----------- Bottom line --------------------------
    if (y_scroll_pos > scrollPosition) {
      $(".line-two").addClass("line-two-animate");
    } else {
      $(".line-two").removeClass("line-two-animate");
    }

    //
    if (y_scroll_pos > scrollPosition) {
       $('.line-one, .line-two').click(function(){
        $menuList.toggleClass('show-menu');
       }); 
    } else {
        return;
        // Items won't be clickable
    }
  });
});`

**Comment by cmaddux** [comment]
All good!

1. I actually think you could make the code most readable/slim by taking some of the repetitive tasks you're doing and moving those into a separate function.

In 3 places you have something similar to this:

```javascript
if (y_scroll_pos > scrollPosition) {
  $menuList.addClass("hide-menu");
} else {
  $menuList.removeClass("hide-menu");
}
```

They could be abstracted away with something like this:

```javascript
/**
 * Toggle a class based on provided comparison.
 *
 * @param {Boolean} shouldAddClass - Determines if class should be added
 * @param {Object} selectedEl - A valid jquery selected element
 * @param {String} class - class to toggle
 *
 * @return {void}
 */
function toggleClassOnBool(shouldAddClass, selector, className) {
    // You could do a check here to make sure selectedEl has 'addClass' and
    // 'removeClass' methods

    if (shouldAddClass) {
        selectedEl.addClass(className);
         return;
    }

    selectedEl.removeClass(className);
}
```

Then the if/else statements look more like this:

```javascript
ver menuList = $('...');
var overScrolled = window.pageYOffset > 250;
toggleClassOnBool(overScrolled, menuList, 'hide-menu');
```

2. It looks like the .off() method (https://www.w3schools.com/jquery/event_off.asp) is the way to go to remove an event handler with jquery. It would be something like this I think:

```javascript
if (y_scroll_pos > scrollPosition) {
   $('.line-one, .line-two').click(function(){
    $menuList.toggleClass('show-menu');
   }); 
} else {
      $('.line-one, .line-two').off('click'); 
}
```

Similar to above, you could create a function like `toggleClickHandlerOnBool(shouldAddClick, selector, clickHandler)` and make that functionailty reusable.

Hope those help! Let me know if any of that didnt make any sense.

**Comment by MichaelIrvine** [comment]
Awesome! Thanks, Cabell.

I think this make sense. I might have to experiment a bit with it to fully understand it.

**Comment by cmaddux** [comment]
Just closing this!

**Comment by MichaelIrvine** [comment]
Thanks Cabell. I never did figure out what you meant by abstracting the code
